---
version: "3"
services:
 devopsdb:
   image: kartheek0976/priya:dbimage1
   ports:
     - "3306:3306"

 application:
   image: kartheek0976/priya:appimage1
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
